/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type BoardPins = {
  imuSDA: string;
  imuSCL: string;
  /**
   * @default 2
   */
  led?: string;
};

export type FirmwareBoardDTO = {
  type:
    | 'BOARD_SLIMEVR'
    | 'BOARD_SLIMEVR_DEV'
    | 'BOARD_NODEMCU'
    | 'BOARD_WROOM32'
    | 'BOARD_WEMOSD1MINI'
    | 'BOARD_TTGO_TBASE'
    | 'BOARD_ESP01';
  pins?: BoardPins;
  /**
   * @default true
   */
  enableLed?: boolean;
  /**
   * @default false
   */
  ledInverted?: boolean;
};

export type IMUConfigDTO = {
  type:
    | 'IMU_MPU9250'
    | 'IMU_MPU6500'
    | 'IMU_BNO080'
    | 'IMU_BNO085'
    | 'IMU_BNO055'
    | 'IMU_BNO086'
    | 'IMU_MPU6050'
    | 'IMU_BMI160'
    | 'IMU_ICM20948'
    | 'IMU_BMI270';
  /**
   * @default 0
   */
  rotation: number;
  imuINT?: string;
};

export type BatteryDTO = {
  type:
    | 'BAT_EXTERNAL'
    | 'BAT_INTERNAL'
    | 'BAT_MCP3021'
    | 'BAT_INTERNAL_MCP3021';
  resistance: number;
  shieldR1: number;
  shieldR2: number;
  pin: string;
};

export type BuildFirmwareDTO = {
  version: string;
  board: FirmwareBoardDTO;
  imus: IMUConfigDTO[];
  battery?: BatteryDTO;
};

export type FirmwareFile = {
  url: string;
  offset: number;
};

export type Firmware = {
  id: string;
  releaseID: string;
  buildStatus: 'BUILDING' | 'DONE' | 'FAILED';
  buildConfig: BuildFirmwareDTO;
  firmwareFiles?: FirmwareFile[];
  /**
   * @format date-time
   */
  creationDate: string;
  /**
   * @format date-time
   */
  updateDate: string;
};

export type BuildResponse = {
  id: string;
  status: 'BUILDING' | 'DONE' | 'FAILED';
  firmwareFiles?: FirmwareFile[];
};

export type BoardTypeBoard = {
  boardType:
    | 'BOARD_SLIMEVR'
    | 'BOARD_SLIMEVR_DEV'
    | 'BOARD_NODEMCU'
    | 'BOARD_WROOM32'
    | 'BOARD_WEMOSD1MINI'
    | 'BOARD_TTGO_TBASE'
    | 'BOARD_ESP01';
  board: string;
};

export type ReleaseDTO = {
  id: string;
  url: string;
  name: string;
  zipball_url: string;
  prerelease: boolean;
  draft: boolean;
};

export type Imudto = {
  type:
    | 'IMU_MPU9250'
    | 'IMU_MPU6500'
    | 'IMU_BNO080'
    | 'IMU_BNO085'
    | 'IMU_BNO055'
    | 'IMU_BNO086'
    | 'IMU_MPU6050'
    | 'IMU_BMI160'
    | 'IMU_ICM20948'
    | 'IMU_BMI270';
  hasIntPin: boolean;
};
